### ISSUE TITLE
Do I need Tdarr Pro for all statistics?

### ISSUE THREAD

**Issue by nick2000713** [homeylab/tdarr-exporter#34]
Hi,

I've set it up in a Docker container and it's working fine, but some statistics are missing. For example, Libarys doesn't show up, while other things seem to be working properly. Do I need Tdarr Pro for all statistics?

**Comment by pchang388** [comment]
hey @nick2000713 

Thanks for raising the issue, I noticed I am also seeeing missing statistics. It appears the API response and input has changed for Tdarr statistics. Previously, the general stats was available through the following API:

```
# body
{
    "data": {
        "collection": "StatisticsJSONDB",
        "mode": "getById",
        "docID": "statistics",
        "obj": {}
    }
}

# endpoint
https://tdarr.example.com/api/v2/cruddb
```

That specific call would return all the general library stats info but now it returns no information for certain fields, example:

```
{
    "_id": "statistics",
    "totalFileCount": 20880,
    "totalTranscodeCount": 34264,
    "totalHealthCheckCount": 55357,
    "sizeDiff": 54.371078485623,
    "DBFetchTime": "1s",
    "DBLoadStatus": "Stable",
    "DBQueue": 0,
    "pies": [],
    ...
}
```

Notice the `pies` field is now empty when it was previously filled with stats for libraries. Looking at Tdarr releases, I believe this was changed in version `2.24.01 [11th August 2024]`.

The API [documentation](https://tdarr.readme.io/reference/post_cruddb) for this API is not very descriptive of the changes or really what to do. 

But I am taking a look and see what I can find out, whether the API has been changed and I need to update the API call or if stats is now behind a Pro license (which I don't have). Will update this thread after I do some digging, thanks again!

**Comment by pchang388** [comment]
I did some searching and found:

![image](https://github.com/user-attachments/assets/aac3067c-967b-42cb-a172-5a215ff525f2)

The behavior of the stats API has changed and general Library stats has been moved to an undocumented API (`api/v2/stats/get-pies`). I'll work on changing the exporter to use the new API and putting a disclaimer for Tdarr version notice, `v2.24.01` or greater, requiring a new version of the exporter to work properly.

I'll go through the new API and try to push a new version out for those running `v2.24.01` or greater

**Comment by nick2000713** [comment]
Wow, thank you so much for the fast response and your motivation to fix this!
Big thanks for the project!

**Comment by pchang388** [comment]
hey @nick2000713 

I have a new version you can try, it's been tested on my end, `1.4.0` or re-pull the `latest` tag to refresh it.

Just some findings/assumptions on the changes made:

Library stats have been moved to their own API endpoint: `/api/v2/stats/get-pies` and a call must be made for each library after getting their details.
- This takes ~1-2 seconds for (my internal) Tdarr instance to respond and with a high amount of libraries, it may high take some time for a metric scrape request to complete. 
- Further investigation is needed to see if there is a different API or parameters to get the data out quicker/easier. 
- Optionally, concurrent calls for library stats is an option if number of connections is capped/configurable if investigation grows stale.

This release attempts to add functionality for new API and also work with existing instances that may respond with the previous API endpoint: `/api/v2/cruddb`.

**Comment by pchang388** [comment]
Created issue on Tdarr for more information to potentially address the concerns more efficiently:  https://github.com/HaveAGitGat/Tdarr/issues/1072#issue-2501793651

**Comment by nick2000713** [comment]
Hi @pchang388,

Thank you very much! I got it to work with the update. I just had to set the scrape_timeout to 50s in the Prometheus config file, but that's no problem for me. Hopefully they won't make any more changes or switch to this undocumented API.

**Comment by pchang388** [comment]
> Hi @pchang388,
> 
> Thank you very much! I got it to work with the update. I just had to set the scrape_timeout to 50s in the Prometheus config file, but that's no problem for me. Hopefully they won't make any more changes or switch to this undocumented API.

I'm still looking into adding some caching to reduce time and number of API calls but for now I quickly added `HTTP_MAX_CONCURRENCY` (default 3) for users to set how many concurrent library stats calls can be made to speed up scraping.

Can you give version `1.4.1` ( or repull latest) a try if possible and play around with that property? With 3, I am able to get a response from a scrape in ~2-3 seconds. I only have 7 libraries though so but you can try increasing it based on your number of libraries. The README has been updated to give more details on this property.

Thanks @nick2000713 !!

**Comment by HaveAGitGat** [comment]
In next version you can see the API Docs here:
![image](https://github.com/user-attachments/assets/267283ca-57fe-4e00-832a-8b3cd578becf)

Can't see a reason to need to change it in future but would create a new endpoint for any changes and keep this one as-is.

**Comment by pchang388** [comment]
> In next version you can see the API Docs here: ![image](https://private-user-images.githubusercontent.com/43864057/364879613-267283ca-57fe-4e00-832a-8b3cd578becf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDY0MDcsIm5iZiI6MTcyNTkwNjEwNywicGF0aCI6Ii80Mzg2NDA1Ny8zNjQ4Nzk2MTMtMjY3MjgzY2EtNTdmZS00ZTAwLTgzMmEtOGIzY2Q1NzhiZWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MjE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZmM1ZTBhMWU1YjFkODljNGIxNjVjOTMzOTRiYmM4ZmU3NWZiNjM5ZGE4ODBjYTdmYjI2NjAyZTVjYjE3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h81sPZJp8Am4Y1TV-ArC2lWVpvT6Kv3e9nGx8WQmMBQ)
> 
> Can't see a reason to need to change it in future but would create a new endpoint for any changes and keep this one as-is.

The man himself! thank you for the update and I will poke around once the new API docs are published to see what can improve here
